version: '3.6'

services:
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - '8000:80'
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./wordpress:/var/www/html
            - ./logs/nginx:/var/log/nginx
        restart: always

    db:
        image: mariadb:latest
        container_name: db
        ports:
            - '3306:3306'
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        restart: always

    wordpress:
        image: wordpress:5.2.0-php7.3-fpm
        container_name: wordpress
        depends_on:
            - db
            - nginx
        ports:
            - '9000:9000'
        volumes:
            - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
            - ./php-fpm.conf:/usr/local/etc/php-fpm/php-fpm.conf
            - ./wordpress:/var/www/html
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
            WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
            WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
        restart: always
