version: '3.6'

services:
  db:
    image: mysql:${MYSQL_VERSION:-latest}
    container_name: db
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
      - ./config/mysql/mysql-custom.cnf:/etc/mysql/conf.d/mysql-custom.cnf
    environment:
      MYSQL_ROOT_PASSWORD: password
    restart: always
  
  nginx:
    image: nginx:${NGINX_VERSION:-latest}
    container_name: nginx
    depends_on:
        - wordpress
    ports:
      - '8000:80'
    volumes:
      - ./config/nginx/wordpress.conf:/etc/nginx/conf.d/wordpress.conf
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
      - ./wordpress:/var/www/html
    restart: always

  wordpress:
    image: wordpress:5.2.0-php7.3-fpm
    container_name: wordpress
    depends_on:
      - db
    ports:
      - '9000:9000'
    volumes:
      - ./logs/php:/var/log/php
    #   - ./config/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./config/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    restart: always


